name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx5120m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.compiler.execution.strategy=in-process
      TERM: dumb

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleDebug

  test:
    runs-on: macOS-latest
    needs: build
    strategy:
      matrix:
        api-level: [23, 26, 29]
    env:
      JAVA_TOOL_OPTIONS: -Xmx3072m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.compiler.execution.strategy=in-process
      TERM: dumb

    steps:
    
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
    - name: Run some unit tests
      run: ./gradlew test --stacktrace
    - name: Unit tests results
      uses: actions/upload-artifact@v1
      with:
        name: unit-tests-results
        path: app/build/reports/tests/testDebugUnitTest/index.html
